### ISSUE TITLE
Don't crash when passed a binary file

### ISSUE THREAD

**Issue by scottsd** [koles/ya-csv#27]
Now it crashes all nodejs app:

```
node_modules/ya-csv/lib/ya-csv.js:131
 throw new Error("separator expected after a closin
Error: separator expected after a closing quote; found 
```

It should handle the error gracefully.

**Comment by koles** [comment]
This has been fixed a long time ago. Ya-csv emits an 'error' event in the case of an error. Sorry for not closing the ticket formally. Error handling has been added to the examples in the README file.
