### ISSUE TITLE
Console.loged reader out put for a large file, and got "... 924 more items" instead of the other items.

### ISSUE THREAD

**Issue by davidfufu** [koles/ya-csv#48]
It's a pretty big csv file. Instead of all the columns, a lot of the output ends with "... X more items". How do I output all of them?

```
var reader = csv.createCsvFileReader('FB-PageFocus-July2017-To-Sept112017.csv', {
    'separator': ',',
    'quote': '"',
    'escape': '"',
    'comment': '',
});
var writer = new csv.CsvWriter(process.stdout);
// reader.addListener('data', function(data) {
//     console.log([ data ]);
// });

reader.addListener('data', function(data) {
    console.log(data);
});

reader.addListener('error', function(e) {
    console.error('Oops!');
});
```

**Comment by koles** [comment]
Is this what you see in your console window or do you see that even if
ya-csv writes the output into a file?

**Comment by davidfufu** [comment]
Hi, it seems it's just for console output. Writing to another file was fine. This is my code right now. Adding an index to the data seems to give me columns, but what if I want to output the data row by row?
```

var csv = require('ya-csv');
var fs = require('fs');
var streamout = fs.createWriteStream("output.txt");

// equivalent of csv.createCsvFileReader('data.csv')
var reader = csv.createCsvFileReader('chosen.csv', {
    'separator': ',',
    'quote': '"',
    'escape': '"',
    'comment': '',
});
var writer = new csv.CsvWriter(process.stdout);

reader.addListener('data', function(data) {
    console.log(data[1]);
    streamout.write(JSON.stringify(data[0]));
});

reader.addListener('error', function(e) {
    console.error('Oops!');
});

```

**Comment by koles** [comment]
I don't think I can help with that as it doesn't seem to be related to
ya-csv. Actually it's your code that produces the console output, right?

I guess it may be something about the settings of your console.

Please let me know if you have any indications it's a ya-csv issue.

Pavel

On Sep 13, 2017 5:26 AM, "davidfufu" <notifications@github.com> wrote:

Hi, it seems it's just for console output. Writing to another file was
fine. This is my code right now. Adding an index to the data seems to give
me columns, but what if I want to output the data row by row?


var csv = require('ya-csv');
var fs = require('fs');
var streamout = fs.createWriteStream("output.txt");

// equivalent of csv.createCsvFileReader('data.csv')
var reader = csv.createCsvFileReader('chosen.csv', {
    'separator': ',',
    'quote': '"',
    'escape': '"',
    'comment': '',
});
var writer = new csv.CsvWriter(process.stdout);

reader.addListener('data', function(data) {
    console.log(data[1]);
    streamout.write(JSON.stringify(data[0]));
});

reader.addListener('error', function(e) {
    console.error('Oops!');
});


—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/koles/ya-csv/issues/48#issuecomment-329151424>, or mute
the thread

**Comment by davidfufu** [comment]
The console output has been resolved. Now, I'm just wondering how I can output the data row by row in ya-csv.


```
var csv = require('ya-csv');
var fs = require('fs');
var streamout = fs.createWriteStream("output.txt");

var reader = csv.createCsvFileReader('myFile.csv', {
    'separator': ',',
    'quote': '"',
    'escape': '"',
    'comment': '',
});
var writer = new csv.CsvWriter(process.stdout);

reader.addListener('data', function(data) {
    console.log(data[0]);
    streamout.write(JSON.stringify(data[0]));
});

reader.addListener('error', function(e) {
    console.error('Oops!');
});
```

My code currently gives me a column of the csv table when I give an index to data such as "data[0]". I'm wondering if there's a ya-csv setting that will make it return rows instead of columns when I give it an index.

For example, if I did data[0], I'd want it to return the first row. What I see right now when I do that is just the first column like below.

```
Post ID

111519035531887_1898820693468370
111519035531887_1895819030435203
111519035531887_1895099177173855
111519035531887_1893797443970695
111519035531887_1888299321187174
```

**Comment by koles** [comment]
Ah, I see. The ya-csv is designed to be stream processor with a minimal memory footprint. 

Can you help me to understand a bigger picture, why do you prefer to access individual rows? Are you looking for a sort of a random access or is it more like about an ability to skip first N rows easily?

**Comment by davidfufu** [comment]
I'm doing some social media analytics and each row is essentially a post with a Post ID, and more data about engagement. It's just easier for me to work with and more logical. However, in the process of writing this, I tried.

```
for (var i =0; i < data.length; i++) {
 	console.log(data[i]);
 	}
```

This gives me each row item by item. Now this confuses me as "data[0]" gives the first column but a for loop with data[i] gives each item in each row.

I guess my question is answered, but I'm just confused now as to why indexing data can switch between rows and columns.

**Comment by davidfufu** [comment]
Hello again lol, disregard the above question. I have another one. The listener listens for  the "data" event,

```
reader.addListener('data', function(data) {
    console.log(data[0]);
    streamout.write(JSON.stringify(data[0]));
});
```

Is there any way for ya-csv to know when the last data event has happened? I'm changing the csv to JSON and I want to let the program know when the last data event has happened so it can append something at the end. Does

**Comment by davidfufu** [comment]
Is there any way for ya-csv to know when the order of the 'data' events? I'd like to have something trigger on the last 'data' event of the stream.

**Comment by koles** [comment]
The 'end' event is triggered when the processing is over. If you hold the
most recent row in a separate variable outside of the 'data' event handler,
you can access that variable in your 'end' event handler. Does it answer
your question?

**Comment by davidfufu** [comment]
Yup, thanks for the help.
